 import type { Metadata } from "next";

import "./globals.css";
import Header from"@/app/components/Header";
import Footer from"@/app/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex mt-4 mb-4">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
